xAPISaverPlugin added
teltek/paella pull request #9
Opened 2017-12-14 12:28 UTC by dpeite

2017-12-21 18:08 UTC, rubenrua commented
@brapifra Could you review this?

2017-12-22 11:17 UTC, brapifra requested changes

2017-12-22 11:17 UTC, brapifra commented on plugins/es.teltek.paella.usertracking.xAPISaverPlugin/xAPISaverPlugin.js
> +				if (self.progress == 1 && self.completed == false){
Strict Equality Comparison (===) should be used

2017-12-22 11:17 UTC, brapifra commented on plugins/es.teltek.paella.usertracking.xAPISaverPlugin/xAPISaverPlugin.js
> +			var self = this
Use const/let

2018-01-11 16:08 UTC, rubenrua commented
Please open a pull request upstream (polimediaupv/paella).

2018-01-11 16:08 UTC, closed without merging